osx_image: xcode10.1
language: objective-c
env:
  global:
    - PROJECT="RealmWrapper.xcodeproj"
    - SCHEME="RealmWrapper"
    - IOS_SDK="iphonesimulator"
  matrix:
    - SDK="$IOS_SDK"      TEST=0  DESTINATION="platform=iOS Simulator,name=iPhone X,OS=12.1"

before_install:
  - brew update
  - if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
  - travis_wait 35 carthage bootstrap --platform iOS

install:
  - swift --version

before_script:
  - set -o pipefail

script:
    - travis_retry xcodebuild clean build test
      -project "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c